circlet {
    packages {
        url = "https://packages.example.com"
        internalUrl = "http://packages:9390"
    }

    space {
        url = "https://space.example.com"
        internalUrl = "http://space:9084"
    }
}