circlet {
    frontend {
        url = "https://space.example.com"
        internalUrl = "http://space:9084"
    }
    packages {
        notifications {
            enabled = true
        }
        types {
            maven {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            nuget {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            npm {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            container {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            pypi {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            composer {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            dart {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }

            files {
                url = "https://packages.example.com"
                internalUrl = "http://packages:9390"
            }
        }
    }
}
