import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, unlinkSync } from "node:fs";
import type {
  DesloppifyIssue,
  IssueCreatorOptions,
  IssueGroup,
  ScanResult,
} from "./types.js";

function loadScanResult(inputPath: string): ScanResult {
  const raw = readFileSync(inputPath, "utf-8");
  return JSON.parse(raw) as ScanResult;
}

function tierLabel(tier: number): string {
  switch (tier) {
    case 1:
      return "T1-critical";
    case 2:
      return "T2-high";
    case 3:
      return "T3-medium";
    case 4:
      return "T4-low";
    default:
      return `T${tier}`;
  }
}

function priorityForTier(tier: number): string {
  if (tier <= 1) return "critical";
  if (tier <= 2) return "high";
  if (tier <= 3) return "medium";
  return "low";
}

function groupByDetector(
  findings: DesloppifyIssue[],
  repoName: string,
): IssueGroup[] {
  const groups = new Map<string, DesloppifyIssue[]>();
  for (const finding of findings) {
    const key = finding.detector;
    const existing = groups.get(key) || [];
    existing.push(finding);
    groups.set(key, existing);
  }

  return Array.from(groups.entries()).map(([detector, items]) => {
    const minTier = Math.min(...items.map((i) => i.tier));
    const fileList = items
      .map((i) => `- \`${i.file}\`: ${i.message}`)
      .join("\n");

    return {
      title: `[desloppify][${repoName}] ${detector}: ${items.length} issue${items.length > 1 ? "s" : ""} (${tierLabel(minTier)})`,
      description: [
        `## desloppify findings — ${detector}`,
        "",
        `**Repo:** ${repoName}`,
        `**Detector:** ${detector}`,
        `**Count:** ${items.length}`,
        `**Severity:** ${tierLabel(minTier)}`,
        "",
        "### Affected files",
        "",
        fileList,
        "",
        "---",
        "*Auto-generated by @aprovan/devtools desloppify-issues*",
      ].join("\n"),
      tier: minTier,
      detector,
      findings: items,
    };
  });
}

function groupByFile(
  findings: DesloppifyIssue[],
  repoName: string,
): IssueGroup[] {
  const groups = new Map<string, DesloppifyIssue[]>();
  for (const finding of findings) {
    const key = finding.file;
    const existing = groups.get(key) || [];
    existing.push(finding);
    groups.set(key, existing);
  }

  return Array.from(groups.entries()).map(([file, items]) => {
    const minTier = Math.min(...items.map((i) => i.tier));
    const detectorList = [...new Set(items.map((i) => i.detector))].join(", ");
    const issueList = items
      .map((i) => `- [${i.detector}] ${i.message}`)
      .join("\n");

    return {
      title: `[desloppify][${repoName}] ${file}: ${items.length} issue${items.length > 1 ? "s" : ""} (${tierLabel(minTier)})`,
      description: [
        `## desloppify findings — ${file}`,
        "",
        `**Repo:** ${repoName}`,
        `**File:** ${file}`,
        `**Detectors:** ${detectorList}`,
        `**Count:** ${items.length}`,
        `**Severity:** ${tierLabel(minTier)}`,
        "",
        "### Issues",
        "",
        issueList,
        "",
        "---",
        "*Auto-generated by @aprovan/devtools desloppify-issues*",
      ].join("\n"),
      tier: minTier,
      detector: detectorList,
      findings: items,
    };
  });
}

function groupByPackage(
  findings: DesloppifyIssue[],
  repoName: string,
  packages: { name: string; path: string }[],
): IssueGroup[] {
  const groups = new Map<string, DesloppifyIssue[]>();
  for (const finding of findings) {
    const pkg =
      packages.find((p) => finding.file.startsWith(p.path + "/")) ||
      packages[0];
    const key = pkg?.name || "root";
    const existing = groups.get(key) || [];
    existing.push(finding);
    groups.set(key, existing);
  }

  return Array.from(groups.entries()).map(([pkgName, items]) => {
    const minTier = Math.min(...items.map((i) => i.tier));
    const detectorList = [...new Set(items.map((i) => i.detector))].join(", ");
    const issueList = items
      .map((i) => `- \`${i.file}\` [${i.detector}]: ${i.message}`)
      .join("\n");

    return {
      title: `[desloppify][${repoName}][${pkgName}] ${items.length} issue${items.length > 1 ? "s" : ""} (${tierLabel(minTier)})`,
      description: [
        `## desloppify findings — ${pkgName}`,
        "",
        `**Repo:** ${repoName}`,
        `**Package:** ${pkgName}`,
        `**Detectors:** ${detectorList}`,
        `**Count:** ${items.length}`,
        `**Severity:** ${tierLabel(minTier)}`,
        "",
        "### Issues",
        "",
        issueList,
        "",
        "---",
        "*Auto-generated by @aprovan/devtools desloppify-issues*",
      ].join("\n"),
      tier: minTier,
      detector: detectorList,
      findings: items,
    };
  });
}

function collectFindings(
  result: ScanResult,
  minTier: number,
): DesloppifyIssue[] {
  const all: DesloppifyIssue[] = [];
  for (const pkg of result.packages) {
    for (const issue of pkg.issues) {
      if (issue.tier <= minTier && issue.status === "open") {
        all.push(issue);
      }
    }
  }
  return all;
}

function groupFindings(
  findings: DesloppifyIssue[],
  result: ScanResult,
  groupBy: "detector" | "file" | "package",
): IssueGroup[] {
  switch (groupBy) {
    case "detector":
      return groupByDetector(findings, result.repo);
    case "file":
      return groupByFile(findings, result.repo);
    case "package":
      return groupByPackage(
        findings,
        result.repo,
        result.packages.map((p) => ({ name: p.name, path: p.path })),
      );
  }
}

function escapeForCli(str: string): string {
  return str.replace(/'/g, "'\\''");
}

function createMulticaIssue(
  group: IssueGroup,
  parent: string | undefined,
  project: string | undefined,
): string {
  const descFile = `/tmp/desloppify-issue-${Date.now()}.md`;
  writeFileSync(descFile, group.description, "utf-8");

  const args = [
    "multica issue create",
    `--title '${escapeForCli(group.title)}'`,
    `--priority ${priorityForTier(group.tier)}`,
    `--description-file '${descFile}'`,
  ];

  if (parent) {
    args.push(`--parent '${parent}'`);
  }

  if (project) {
    args.push(`--project '${project}'`);
  }

  const cmd = args.join(" ");

  let output = "";
  try {
    output = execSync(cmd, {
      encoding: "utf-8",
      shell: "/bin/bash",
      timeout: 30_000,
    }).trim();
  } finally {
    try {
      unlinkSync(descFile);
    } catch {
      // best-effort cleanup
    }
  }

  return output;
}

export function createDesloppifyIssues(
  options: IssueCreatorOptions,
): { created: number; skipped: number; groups: IssueGroup[] } {
  const {
    input,
    repo,
    parent,
    project,
    minTier = 2,
    dryRun = false,
    groupBy = "detector",
  } = options;

  const result = loadScanResult(input);

  if (result.repo !== repo) {
    console.warn(
      `Warning: scan result repo "${result.repo}" differs from --repo "${repo}"`,
    );
  }

  const findings = collectFindings(result, minTier);

  if (findings.length === 0) {
    console.log(`No T1-T${minTier} open findings found. Nothing to create.`);
    return { created: 0, skipped: 0, groups: [] };
  }

  console.log(
    `Found ${findings.length} T1-T${minTier} open findings across ${result.repo}.`,
  );

  const groups = groupFindings(findings, result, groupBy);

  console.log(
    `Grouped into ${groups.length} issue${groups.length > 1 ? "s" : ""} by "${groupBy}".`,
  );

  let created = 0;
  let skipped = 0;

  for (const group of groups) {
    if (dryRun) {
      console.log("\n[DRY RUN] Would create issue:");
      console.log(`  Title: ${group.title}`);
      console.log(
        `  Priority: ${priorityForTier(group.tier)}`,
      );
      console.log(`  Findings: ${group.findings.length}`);
      console.log(`  Detector: ${group.detector}`);
      skipped++;
    } else {
      try {
        const output = createMulticaIssue(group, parent, project);
        console.log(`Created issue: ${group.title}`);
        if (output) {
          console.log(`  → ${output}`);
        }
        created++;
      } catch (err) {
        console.error(
          `Failed to create issue "${group.title}": ${String(err)}`,
        );
        skipped++;
      }
    }
  }

  return { created, skipped, groups };
}
